class PolicialTips {
  static const List<String> list = [
    'CONSEJO: Para evitar la invalidez procesal, toda acta debe contener siempre la firma del funcionario policial que la redacta y dirige (Art. 121 CPP)',
    'CONSEJO: Evite la nulidad por falta de certeza identificando plenamente a todos los efectivos intervinientes con grado, nombres, apellidos y CIP, evitando firmas genéricas',
    'CONSEJO: Destierre el vicio del "policía superman", donde un mismo efectivo figura redactando múltiples actas en distintos lugares exactamente a la misma hora',
    'CONSEJO: Anule la figura del "fiscal superman", asegurándose de que los tiempos consignados reflejen su participación real y lógica sin horarios superpuestos',
    'CONSEJO: Evite invalidar su propia intervención con el "detenido superman"; un imputado no puede firmar cinco diligencias distintas a la misma hora exacta',
    'CONSEJO: Para que todas las "actas hijas" tengan valor legal pleno, comunique la flagrancia de inmediato al Fiscal de Turno y deje constancia expresa de dicha llamada en el "Acta Madre" de Intervención (Art. 67 CPP)',
    'CONSEJO: Si el Fiscal no atiende el teléfono, deje constancia de la omisión y justifique que se ejecutaron las diligencias de urgencia e imprescindibles para no perder los indicios',
    'CONSEJO: Absténgase de usar el formato "para-para" (ej. "para drogas negativo"); inventar que no halló especies que nadie le pidió buscar ha causado exclusión de actas en juicio',
    'CONSEJO: No consigne que alguien fue intervenido en "actitud sospechosa" sin describir los hechos físicos; el uso de términos subjetivos ocasiona la exclusión de la prueba',
    'CONSEJO: Jamás tache, borre o use corrector ("liquid paper") en un acta; cualquier alteración física compromete la autenticidad y causa su nulidad',
    'CONSEJO: Para subsanar errores de escritura in situ sin anular el acta, abra paréntesis, encierre el texto errado, y consigne de forma expresa la corrección a continuación',
    'CONSEJO: La falta de firma del intervenido no anula el acta siempre y cuando usted deje constancia clara de su negativa y existan otros elementos de convicción (RN N° 298-2023)',
    'CONSEJO: Para validar la falta de rúbrica, es imperativo escribir literalmente "se negó a firmar", "no quiso firmar" o "se rehusó a firmar" en el espacio correspondiente',
    'CONSEJO: Como candado final de validez, debe asentar en la misma acta las razones precisas por las que el imputado alegó negarse a firmar',
    'CONSEJO: Si el imputado no sabe firmar (analfabeto) o no puede hacerlo, evite nulidades pidiendo que un testigo de actuación firme a su ruego e imprimiendo su huella digital',
    'CONSEJO: Un acta redactada en la comisaría es legal, pero para evitar su exclusión debe justificar las "circunstancias apremiantes" (riesgo de fuga, seguridad del policía, lluvia o multitud) que le impidieron formularla in situ',
    'CONSEJO: Nunca realice allanamientos ni registros alegando "acciones de inteligencia" sin una resolución fiscal o judicial; toda evidencia recolectada así será declarada nula y excluida',
    'CONSEJO: En el Acta de Allanamiento sin orden judicial, blinde el ingreso marcando la causal de excepción constitucional exacta: "flagrancia" o "peligro inminente"',
    'CONSEJO: Cuide la cronología: las actas se anulan si la hora de cierre del Acta de Intervención es incongruente o posterior a las actas de registro consecuentes',
    'CONSEJO: Tenga presente que la hora consignada en el encabezado corresponde al momento de la redacción del acta, no necesariamente al instante del hecho delictivo, evitando fatales contradicciones (Casación 97-2023)',
    'CONSEJO: Para asegurar la intangibilidad del documento, rellene con líneas discontinuadas todos los espacios en blanco sobrantes impidiendo que la defensa agregue texto',
    'CONSEJO: En casos de arresto ciudadano, eluda denuncias por privación ilegítima formulando el "Acta de Recepción de Persona Arrestada" con la identidad del ciudadano captor',
    'CONSEJO: Para que este arresto no caiga en irregularidad, obligue a que el ciudadano que entregó al delincuente firme y lea dicha Acta de Recepción',
    'CONSEJO: En operativos inminentes de "revelación del delito" sin presencia fiscal, el Ministerio Público debe apersonarse lo más pronto posible a la escena para convalidar todos sus actos de urgencia',
    'CONSEJO: Nunca conduzca Reconocimientos Físicos informales en la calle; este acto es dirigido por el Fiscal con presencia del abogado defensor',
    'CONSEJO: Al ejecutar un Reconocimiento, anule impugnaciones asegurando que la víctima no tenga contacto físico ni visual previo con el detenido',
    'CONSEJO: El reconocimiento procesalmente válido exige colocar al imputado junto a por lo menos cinco (05) personas de aspecto físico similar',
    'CONSEJO: Folie todo el expediente usando números arábigos correlativos en la esquina superior derecha, previniendo la sustracción de páginas por partes interesadas',
    'CONSEJO: Escriba las cantidades de drogas, armas o dinero obligatoriamente en mayúsculas, seguidas de la cantidad en números entre paréntesis, impidiendo modificaciones numéricas',
    'CONSEJO: Si utiliza grabaciones de video o audio en un registro, consígnelo en el acta y transcriba su contenido a una nueva acta para que tenga peso de medio de prueba admisible',
    'CONSEJO: Durante la primera manifestación, pregunte expresamente al detenido si requiere el asesoramiento de un abogado defensor; no hacerlo causa nulidad por indefensión',
    'CONSEJO: Si el imputado es extranjero o quechuahablante, consiga un traductor y hágalo firmar el acta; tomar declaraciones en idiomas no comprendidos vicia todo el acto',
    'CONSEJO: Prohíba emplear términos como "se procede a levantar el acta", ya que procesalmente y tácticamente lo correcto es "se procede a realizar la diligencia"',
    'CONSEJO: Al interrogar a testigos, eluda la nulidad por sugestión; no formule preguntas cerradas o ambiguas, y escriba las respuestas copiando la expresión literal en primera persona',
    'CONSEJO: Evite nombrar vehículos genéricamente como "cincuenta combis", ya que la falta de exactitud técnica (microbús, minibús) permite al abogado desvirtuar la pericia',
    'CONSEJO: Al encontrar anexos muy amplios, numérelos de forma correlativa (Anexo 1A, 1B), cerrando la brecha a la pérdida intencional de folios',
    'CONSEJO: Redacte detalladamente en la sección correspondiente el "estado de conservación" de los bienes incautados para neutralizar denuncias por "sembrado" o "daños" policiales',
    'CONSEJO: Cierre la cadena de custodia asegurando que las denominaciones en el Acta de Lacrado, Hallazgo e Incautación coincidan al milímetro con lo dictado en el Formato A-6',
    'CONSEJO: Para convalidar "vicios formales subsanables" (Nulidad Relativa), realice el saneamiento procesal rectificando el error o cumpliendo el acto omitido antes de que precluya la etapa (Art. 153 CPP)',
    'CONSEJO: Una nulidad absoluta por violación de garantías constitucionales generará un "efecto dominó", anulando todos los actos consecutivos que deriven de ella (Art. 154 CPP)',
    'CONSEJO: En toda manifestación investigatoria en la delegación, garantice la presencia del representante del Ministerio Público, a menos que se justifique fuerza mayor ineludible',
    'CONSEJO: Use siempre el sello redondo de su Unidad y estampe su post-firma (CIP, Grado y Nombres); actas huérfanas de validación institucional carecen de firmeza',
    'CONSEJO: Indique obligatoriamente en toda diligencia el lugar, año, mes, día y la hora de redacción para establecer certeza jurídica indubitable (Art. 120 CPP)',
    'CONSEJO: La omisión de formalidades solo torna invalorable un acta si no puede ser suplida mediante la interconexión técnica con otras actuaciones conexas (Art. 121 CPP)',
    'CONSEJO: Individualice las acciones ("El suboficial X procedió al decomiso"); diluir acciones bajo "el personal interviniente" genera exclusiones por indeterminación probatoria',
    'CONSEJO: En situaciones donde no pueda determinar marcas balísticas in situ (ej. fragmentación), consigne dictámenes como "no concluyente" en lugar de hacer presunciones sin respaldo',
    'CONSEJO: Cuando tome muestras gráficas o firmas de cotejo, impida que el sospechoso observe el documento dubitado (falso); dicte el texto variando las velocidades para anular intentos de disfrazar la letra',
    'CONSEJO: Formule estrictamente el Formato de Lectura de Derechos de forma inmediata a la privación de libertad; si el juez advierte que los derechos se leyeron horas después de la captura, excluirá la incautación inicial',
    'CONSEJO: Para todo término institucional o técnico que emplee por primera vez, escriba la palabra completa y luego sus siglas entre paréntesis para bloquear malas interpretaciones semánticas',
    'CONSEJO: Si usa "Constancias de Buen Trato", resérvelas única y exclusivamente para diligencias de Violencia Familiar y Control de Identidad; su uso automatizado en casos de drogas o armas de fuego es una mala práctica invalidable',
  ];
}
